// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface GuestOsFeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.GuestOsFeature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of a supported feature. Read Enabling guest operating system features to see a list of available options.
   * Check the Type enum for the list of possible values.
   * </pre>
   *
   * <code>optional string type = 3575610;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   * The ID of a supported feature. Read Enabling guest operating system features to see a list of available options.
   * Check the Type enum for the list of possible values.
   * </pre>
   *
   * <code>optional string type = 3575610;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * The ID of a supported feature. Read Enabling guest operating system features to see a list of available options.
   * Check the Type enum for the list of possible values.
   * </pre>
   *
   * <code>optional string type = 3575610;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
