// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface HttpFaultDelayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.HttpFaultDelay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Specifies the value of the fixed delay interval.
   * </pre>
   *
   * <code>optional .google.cloud.compute.v1.Duration fixed_delay = 317037816;</code>
   * @return Whether the fixedDelay field is set.
   */
  boolean hasFixedDelay();
  /**
   * <pre>
   * Specifies the value of the fixed delay interval.
   * </pre>
   *
   * <code>optional .google.cloud.compute.v1.Duration fixed_delay = 317037816;</code>
   * @return The fixedDelay.
   */
  com.google.cloud.compute.v1.Duration getFixedDelay();
  /**
   * <pre>
   * Specifies the value of the fixed delay interval.
   * </pre>
   *
   * <code>optional .google.cloud.compute.v1.Duration fixed_delay = 317037816;</code>
   */
  com.google.cloud.compute.v1.DurationOrBuilder getFixedDelayOrBuilder();

  /**
   * <pre>
   * The percentage of traffic (connections/operations/requests) on which delay will be introduced as part of fault injection. The value must be between 0.0 and 100.0 inclusive.
   * </pre>
   *
   * <code>optional double percentage = 151909018;</code>
   * @return Whether the percentage field is set.
   */
  boolean hasPercentage();
  /**
   * <pre>
   * The percentage of traffic (connections/operations/requests) on which delay will be introduced as part of fault injection. The value must be between 0.0 and 100.0 inclusive.
   * </pre>
   *
   * <code>optional double percentage = 151909018;</code>
   * @return The percentage.
   */
  double getPercentage();
}
