// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface LocationPolicyLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.LocationPolicyLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Preference for a given location: ALLOW or DENY.
   * Check the Preference enum for the list of possible values.
   * </pre>
   *
   * <code>optional string preference = 150781147;</code>
   * @return Whether the preference field is set.
   */
  boolean hasPreference();
  /**
   * <pre>
   * Preference for a given location: ALLOW or DENY.
   * Check the Preference enum for the list of possible values.
   * </pre>
   *
   * <code>optional string preference = 150781147;</code>
   * @return The preference.
   */
  java.lang.String getPreference();
  /**
   * <pre>
   * Preference for a given location: ALLOW or DENY.
   * Check the Preference enum for the list of possible values.
   * </pre>
   *
   * <code>optional string preference = 150781147;</code>
   * @return The bytes for preference.
   */
  com.google.protobuf.ByteString
      getPreferenceBytes();
}
