// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface RequestMirrorPolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.RequestMirrorPolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The full or partial URL to the BackendService resource being mirrored to.
   * </pre>
   *
   * <code>optional string backend_service = 306946058;</code>
   * @return Whether the backendService field is set.
   */
  boolean hasBackendService();
  /**
   * <pre>
   * The full or partial URL to the BackendService resource being mirrored to.
   * </pre>
   *
   * <code>optional string backend_service = 306946058;</code>
   * @return The backendService.
   */
  java.lang.String getBackendService();
  /**
   * <pre>
   * The full or partial URL to the BackendService resource being mirrored to.
   * </pre>
   *
   * <code>optional string backend_service = 306946058;</code>
   * @return The bytes for backendService.
   */
  com.google.protobuf.ByteString
      getBackendServiceBytes();
}
