// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface ResourcePolicyGroupPlacementPolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.ResourcePolicyGroupPlacementPolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of availability domains instances will be spread across. If two instances are in different availability domain, they will not be put in the same low latency network
   * </pre>
   *
   * <code>optional int32 availability_domain_count = 12453432;</code>
   * @return Whether the availabilityDomainCount field is set.
   */
  boolean hasAvailabilityDomainCount();
  /**
   * <pre>
   * The number of availability domains instances will be spread across. If two instances are in different availability domain, they will not be put in the same low latency network
   * </pre>
   *
   * <code>optional int32 availability_domain_count = 12453432;</code>
   * @return The availabilityDomainCount.
   */
  int getAvailabilityDomainCount();

  /**
   * <pre>
   * Specifies network collocation
   * Check the Collocation enum for the list of possible values.
   * </pre>
   *
   * <code>optional string collocation = 511156533;</code>
   * @return Whether the collocation field is set.
   */
  boolean hasCollocation();
  /**
   * <pre>
   * Specifies network collocation
   * Check the Collocation enum for the list of possible values.
   * </pre>
   *
   * <code>optional string collocation = 511156533;</code>
   * @return The collocation.
   */
  java.lang.String getCollocation();
  /**
   * <pre>
   * Specifies network collocation
   * Check the Collocation enum for the list of possible values.
   * </pre>
   *
   * <code>optional string collocation = 511156533;</code>
   * @return The bytes for collocation.
   */
  com.google.protobuf.ByteString
      getCollocationBytes();

  /**
   * <pre>
   * Number of vms in this placement group
   * </pre>
   *
   * <code>optional int32 vm_count = 261463431;</code>
   * @return Whether the vmCount field is set.
   */
  boolean hasVmCount();
  /**
   * <pre>
   * Number of vms in this placement group
   * </pre>
   *
   * <code>optional int32 vm_count = 261463431;</code>
   * @return The vmCount.
   */
  int getVmCount();
}
