/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

/**
 *
 *
 * <pre>
 * Message containing what to include in the cache key for a request for Cloud CDN.
 * </pre>
 *
 * Protobuf type {@code google.cloud.compute.v1.CacheKeyPolicy}
 */
public final class CacheKeyPolicy extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.compute.v1.CacheKeyPolicy)
    CacheKeyPolicyOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use CacheKeyPolicy.newBuilder() to construct.
  private CacheKeyPolicy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CacheKeyPolicy() {
    queryStringExcludelist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    queryStringIncludelist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new CacheKeyPolicy();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private CacheKeyPolicy(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 419651970:
            {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                queryStringIncludelist_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              queryStringIncludelist_.add(s);
              break;
            }
          case -1866907016:
            {
              bitField0_ |= 0x00000002;
              includeProtocol_ = input.readBool();
              break;
            }
          case -1455249358:
            {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                queryStringExcludelist_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              queryStringExcludelist_.add(s);
              break;
            }
          case -502674184:
            {
              bitField0_ |= 0x00000004;
              includeQueryString_ = input.readBool();
              break;
            }
          case -400025864:
            {
              bitField0_ |= 0x00000001;
              includeHost_ = input.readBool();
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        queryStringIncludelist_ = queryStringIncludelist_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        queryStringExcludelist_ = queryStringExcludelist_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.compute.v1.Compute
        .internal_static_google_cloud_compute_v1_CacheKeyPolicy_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.compute.v1.Compute
        .internal_static_google_cloud_compute_v1_CacheKeyPolicy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.compute.v1.CacheKeyPolicy.class,
            com.google.cloud.compute.v1.CacheKeyPolicy.Builder.class);
  }

  private int bitField0_;
  public static final int INCLUDE_HOST_FIELD_NUMBER = 486867679;
  private boolean includeHost_;
  /**
   *
   *
   * <pre>
   * If true, requests to different hosts will be cached separately.
   * </pre>
   *
   * <code>bool include_host = 486867679;</code>
   *
   * @return Whether the includeHost field is set.
   */
  @java.lang.Override
  public boolean hasIncludeHost() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   *
   *
   * <pre>
   * If true, requests to different hosts will be cached separately.
   * </pre>
   *
   * <code>bool include_host = 486867679;</code>
   *
   * @return The includeHost.
   */
  @java.lang.Override
  public boolean getIncludeHost() {
    return includeHost_;
  }

  public static final int INCLUDE_PROTOCOL_FIELD_NUMBER = 303507535;
  private boolean includeProtocol_;
  /**
   *
   *
   * <pre>
   * If true, http and https requests will be cached separately.
   * </pre>
   *
   * <code>bool include_protocol = 303507535;</code>
   *
   * @return Whether the includeProtocol field is set.
   */
  @java.lang.Override
  public boolean hasIncludeProtocol() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   *
   *
   * <pre>
   * If true, http and https requests will be cached separately.
   * </pre>
   *
   * <code>bool include_protocol = 303507535;</code>
   *
   * @return The includeProtocol.
   */
  @java.lang.Override
  public boolean getIncludeProtocol() {
    return includeProtocol_;
  }

  public static final int INCLUDE_QUERY_STRING_FIELD_NUMBER = 474036639;
  private boolean includeQueryString_;
  /**
   *
   *
   * <pre>
   * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
   * </pre>
   *
   * <code>bool include_query_string = 474036639;</code>
   *
   * @return Whether the includeQueryString field is set.
   */
  @java.lang.Override
  public boolean hasIncludeQueryString() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   *
   *
   * <pre>
   * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
   * </pre>
   *
   * <code>bool include_query_string = 474036639;</code>
   *
   * @return The includeQueryString.
   */
  @java.lang.Override
  public boolean getIncludeQueryString() {
    return includeQueryString_;
  }

  public static final int QUERY_STRING_BLACKLIST_FIELD_NUMBER = 354964742;
  private com.google.protobuf.LazyStringList queryStringExcludelist_;
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @return A list containing the queryStringExcludelist.
   */
  public com.google.protobuf.ProtocolStringList getQueryStringExcludelistList() {
    return queryStringExcludelist_;
  }
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @return The count of queryStringExcludelist.
   */
  public int getQueryStringExcludelistCount() {
    return queryStringExcludelist_.size();
  }
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @param index The index of the element to return.
   * @return The queryStringExcludelist at the given index.
   */
  public java.lang.String getQueryStringExcludelist(int index) {
    return queryStringExcludelist_.get(index);
  }
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the queryStringExcludelist at the given index.
   */
  public com.google.protobuf.ByteString getQueryStringExcludelistBytes(int index) {
    return queryStringExcludelist_.getByteString(index);
  }

  public static final int QUERY_STRING_WHITELIST_FIELD_NUMBER = 52456496;
  private com.google.protobuf.LazyStringList queryStringIncludelist_;
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @return A list containing the queryStringIncludelist.
   */
  public com.google.protobuf.ProtocolStringList getQueryStringIncludelistList() {
    return queryStringIncludelist_;
  }
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @return The count of queryStringIncludelist.
   */
  public int getQueryStringIncludelistCount() {
    return queryStringIncludelist_.size();
  }
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @param index The index of the element to return.
   * @return The queryStringIncludelist at the given index.
   */
  public java.lang.String getQueryStringIncludelist(int index) {
    return queryStringIncludelist_.get(index);
  }
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the queryStringIncludelist at the given index.
   */
  public com.google.protobuf.ByteString getQueryStringIncludelistBytes(int index) {
    return queryStringIncludelist_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    for (int i = 0; i < queryStringIncludelist_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(
          output, 52456496, queryStringIncludelist_.getRaw(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(303507535, includeProtocol_);
    }
    for (int i = 0; i < queryStringExcludelist_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(
          output, 354964742, queryStringExcludelist_.getRaw(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(474036639, includeQueryString_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(486867679, includeHost_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < queryStringIncludelist_.size(); i++) {
        dataSize += computeStringSizeNoTag(queryStringIncludelist_.getRaw(i));
      }
      size += dataSize;
      size += 5 * getQueryStringIncludelistList().size();
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(303507535, includeProtocol_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < queryStringExcludelist_.size(); i++) {
        dataSize += computeStringSizeNoTag(queryStringExcludelist_.getRaw(i));
      }
      size += dataSize;
      size += 5 * getQueryStringExcludelistList().size();
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(474036639, includeQueryString_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(486867679, includeHost_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.compute.v1.CacheKeyPolicy)) {
      return super.equals(obj);
    }
    com.google.cloud.compute.v1.CacheKeyPolicy other =
        (com.google.cloud.compute.v1.CacheKeyPolicy) obj;

    if (hasIncludeHost() != other.hasIncludeHost()) return false;
    if (hasIncludeHost()) {
      if (getIncludeHost() != other.getIncludeHost()) return false;
    }
    if (hasIncludeProtocol() != other.hasIncludeProtocol()) return false;
    if (hasIncludeProtocol()) {
      if (getIncludeProtocol() != other.getIncludeProtocol()) return false;
    }
    if (hasIncludeQueryString() != other.hasIncludeQueryString()) return false;
    if (hasIncludeQueryString()) {
      if (getIncludeQueryString() != other.getIncludeQueryString()) return false;
    }
    if (!getQueryStringExcludelistList().equals(other.getQueryStringExcludelistList())) return false;
    if (!getQueryStringIncludelistList().equals(other.getQueryStringIncludelistList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIncludeHost()) {
      hash = (37 * hash) + INCLUDE_HOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getIncludeHost());
    }
    if (hasIncludeProtocol()) {
      hash = (37 * hash) + INCLUDE_PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getIncludeProtocol());
    }
    if (hasIncludeQueryString()) {
      hash = (37 * hash) + INCLUDE_QUERY_STRING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getIncludeQueryString());
    }
    if (getQueryStringExcludelistCount() > 0) {
      hash = (37 * hash) + QUERY_STRING_BLACKLIST_FIELD_NUMBER;
      hash = (53 * hash) + getQueryStringExcludelistList().hashCode();
    }
    if (getQueryStringIncludelistCount() > 0) {
      hash = (37 * hash) + QUERY_STRING_WHITELIST_FIELD_NUMBER;
      hash = (53 * hash) + getQueryStringIncludelistList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.cloud.compute.v1.CacheKeyPolicy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Message containing what to include in the cache key for a request for Cloud CDN.
   * </pre>
   *
   * Protobuf type {@code google.cloud.compute.v1.CacheKeyPolicy}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.compute.v1.CacheKeyPolicy)
      com.google.cloud.compute.v1.CacheKeyPolicyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.compute.v1.Compute
          .internal_static_google_cloud_compute_v1_CacheKeyPolicy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.compute.v1.Compute
          .internal_static_google_cloud_compute_v1_CacheKeyPolicy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.compute.v1.CacheKeyPolicy.class,
              com.google.cloud.compute.v1.CacheKeyPolicy.Builder.class);
    }

    // Construct using com.google.cloud.compute.v1.CacheKeyPolicy.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      includeHost_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      includeProtocol_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      includeQueryString_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      queryStringExcludelist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      queryStringIncludelist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.compute.v1.Compute
          .internal_static_google_cloud_compute_v1_CacheKeyPolicy_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.compute.v1.CacheKeyPolicy getDefaultInstanceForType() {
      return com.google.cloud.compute.v1.CacheKeyPolicy.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.compute.v1.CacheKeyPolicy build() {
      com.google.cloud.compute.v1.CacheKeyPolicy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.compute.v1.CacheKeyPolicy buildPartial() {
      com.google.cloud.compute.v1.CacheKeyPolicy result =
          new com.google.cloud.compute.v1.CacheKeyPolicy(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.includeHost_ = includeHost_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.includeProtocol_ = includeProtocol_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.includeQueryString_ = includeQueryString_;
        to_bitField0_ |= 0x00000004;
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        queryStringExcludelist_ = queryStringExcludelist_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.queryStringExcludelist_ = queryStringExcludelist_;
      if (((bitField0_ & 0x00000010) != 0)) {
        queryStringIncludelist_ = queryStringIncludelist_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.queryStringIncludelist_ = queryStringIncludelist_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.compute.v1.CacheKeyPolicy) {
        return mergeFrom((com.google.cloud.compute.v1.CacheKeyPolicy) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.compute.v1.CacheKeyPolicy other) {
      if (other == com.google.cloud.compute.v1.CacheKeyPolicy.getDefaultInstance()) return this;
      if (other.hasIncludeHost()) {
        setIncludeHost(other.getIncludeHost());
      }
      if (other.hasIncludeProtocol()) {
        setIncludeProtocol(other.getIncludeProtocol());
      }
      if (other.hasIncludeQueryString()) {
        setIncludeQueryString(other.getIncludeQueryString());
      }
      if (!other.queryStringExcludelist_.isEmpty()) {
        if (queryStringExcludelist_.isEmpty()) {
          queryStringExcludelist_ = other.queryStringExcludelist_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureQueryStringExcludelistIsMutable();
          queryStringExcludelist_.addAll(other.queryStringExcludelist_);
        }
        onChanged();
      }
      if (!other.queryStringIncludelist_.isEmpty()) {
        if (queryStringIncludelist_.isEmpty()) {
          queryStringIncludelist_ = other.queryStringIncludelist_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureQueryStringIncludelistIsMutable();
          queryStringIncludelist_.addAll(other.queryStringIncludelist_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.compute.v1.CacheKeyPolicy parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.compute.v1.CacheKeyPolicy) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private boolean includeHost_;
    /**
     *
     *
     * <pre>
     * If true, requests to different hosts will be cached separately.
     * </pre>
     *
     * <code>bool include_host = 486867679;</code>
     *
     * @return Whether the includeHost field is set.
     */
    @java.lang.Override
    public boolean hasIncludeHost() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     *
     *
     * <pre>
     * If true, requests to different hosts will be cached separately.
     * </pre>
     *
     * <code>bool include_host = 486867679;</code>
     *
     * @return The includeHost.
     */
    @java.lang.Override
    public boolean getIncludeHost() {
      return includeHost_;
    }
    /**
     *
     *
     * <pre>
     * If true, requests to different hosts will be cached separately.
     * </pre>
     *
     * <code>bool include_host = 486867679;</code>
     *
     * @param value The includeHost to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeHost(boolean value) {
      bitField0_ |= 0x00000001;
      includeHost_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * If true, requests to different hosts will be cached separately.
     * </pre>
     *
     * <code>bool include_host = 486867679;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearIncludeHost() {
      bitField0_ = (bitField0_ & ~0x00000001);
      includeHost_ = false;
      onChanged();
      return this;
    }

    private boolean includeProtocol_;
    /**
     *
     *
     * <pre>
     * If true, http and https requests will be cached separately.
     * </pre>
     *
     * <code>bool include_protocol = 303507535;</code>
     *
     * @return Whether the includeProtocol field is set.
     */
    @java.lang.Override
    public boolean hasIncludeProtocol() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     *
     *
     * <pre>
     * If true, http and https requests will be cached separately.
     * </pre>
     *
     * <code>bool include_protocol = 303507535;</code>
     *
     * @return The includeProtocol.
     */
    @java.lang.Override
    public boolean getIncludeProtocol() {
      return includeProtocol_;
    }
    /**
     *
     *
     * <pre>
     * If true, http and https requests will be cached separately.
     * </pre>
     *
     * <code>bool include_protocol = 303507535;</code>
     *
     * @param value The includeProtocol to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeProtocol(boolean value) {
      bitField0_ |= 0x00000002;
      includeProtocol_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * If true, http and https requests will be cached separately.
     * </pre>
     *
     * <code>bool include_protocol = 303507535;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearIncludeProtocol() {
      bitField0_ = (bitField0_ & ~0x00000002);
      includeProtocol_ = false;
      onChanged();
      return this;
    }

    private boolean includeQueryString_;
    /**
     *
     *
     * <pre>
     * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
     * </pre>
     *
     * <code>bool include_query_string = 474036639;</code>
     *
     * @return Whether the includeQueryString field is set.
     */
    @java.lang.Override
    public boolean hasIncludeQueryString() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     *
     *
     * <pre>
     * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
     * </pre>
     *
     * <code>bool include_query_string = 474036639;</code>
     *
     * @return The includeQueryString.
     */
    @java.lang.Override
    public boolean getIncludeQueryString() {
      return includeQueryString_;
    }
    /**
     *
     *
     * <pre>
     * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
     * </pre>
     *
     * <code>bool include_query_string = 474036639;</code>
     *
     * @param value The includeQueryString to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeQueryString(boolean value) {
      bitField0_ |= 0x00000004;
      includeQueryString_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
     * </pre>
     *
     * <code>bool include_query_string = 474036639;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearIncludeQueryString() {
      bitField0_ = (bitField0_ & ~0x00000004);
      includeQueryString_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList queryStringExcludelist_ =
        com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureQueryStringExcludelistIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        queryStringExcludelist_ = new com.google.protobuf.LazyStringArrayList(queryStringExcludelist_);
        bitField0_ |= 0x00000008;
      }
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @return A list containing the queryStringExcludelist.
     */
    public com.google.protobuf.ProtocolStringList getQueryStringExcludelistList() {
      return queryStringExcludelist_.getUnmodifiableView();
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @return The count of queryStringExcludelist.
     */
    public int getQueryStringExcludelistCount() {
      return queryStringExcludelist_.size();
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @param index The index of the element to return.
     * @return The queryStringExcludelist at the given index.
     */
    public java.lang.String getQueryStringExcludelist(int index) {
      return queryStringExcludelist_.get(index);
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the queryStringExcludelist at the given index.
     */
    public com.google.protobuf.ByteString getQueryStringExcludelistBytes(int index) {
      return queryStringExcludelist_.getByteString(index);
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @param index The index to set the value at.
     * @param value The queryStringExcludelist to set.
     * @return This builder for chaining.
     */
    public Builder setQueryStringExcludelist(int index, java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureQueryStringExcludelistIsMutable();
      queryStringExcludelist_.set(index, value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @param value The queryStringExcludelist to add.
     * @return This builder for chaining.
     */
    public Builder addQueryStringExcludelist(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureQueryStringExcludelistIsMutable();
      queryStringExcludelist_.add(value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @param values The queryStringExcludelist to add.
     * @return This builder for chaining.
     */
    public Builder addAllQueryStringExcludelist(java.lang.Iterable<java.lang.String> values) {
      ensureQueryStringExcludelistIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, queryStringExcludelist_);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearQueryStringExcludelist() {
      queryStringExcludelist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_excludelist = 354964742;</code>
     *
     * @param value The bytes of the queryStringExcludelist to add.
     * @return This builder for chaining.
     */
    public Builder addQueryStringExcludelistBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureQueryStringExcludelistIsMutable();
      queryStringExcludelist_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList queryStringIncludelist_ =
        com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureQueryStringIncludelistIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        queryStringIncludelist_ = new com.google.protobuf.LazyStringArrayList(queryStringIncludelist_);
        bitField0_ |= 0x00000010;
      }
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @return A list containing the queryStringIncludelist.
     */
    public com.google.protobuf.ProtocolStringList getQueryStringIncludelistList() {
      return queryStringIncludelist_.getUnmodifiableView();
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @return The count of queryStringIncludelist.
     */
    public int getQueryStringIncludelistCount() {
      return queryStringIncludelist_.size();
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @param index The index of the element to return.
     * @return The queryStringIncludelist at the given index.
     */
    public java.lang.String getQueryStringIncludelist(int index) {
      return queryStringIncludelist_.get(index);
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the queryStringIncludelist at the given index.
     */
    public com.google.protobuf.ByteString getQueryStringIncludelistBytes(int index) {
      return queryStringIncludelist_.getByteString(index);
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @param index The index to set the value at.
     * @param value The queryStringIncludelist to set.
     * @return This builder for chaining.
     */
    public Builder setQueryStringIncludelist(int index, java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureQueryStringIncludelistIsMutable();
      queryStringIncludelist_.set(index, value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @param value The queryStringIncludelist to add.
     * @return This builder for chaining.
     */
    public Builder addQueryStringIncludelist(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureQueryStringIncludelistIsMutable();
      queryStringIncludelist_.add(value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @param values The queryStringIncludelist to add.
     * @return This builder for chaining.
     */
    public Builder addAllQueryStringIncludelist(java.lang.Iterable<java.lang.String> values) {
      ensureQueryStringIncludelistIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, queryStringIncludelist_);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearQueryStringIncludelist() {
      queryStringIncludelist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
     * </pre>
     *
     * <code>repeated string query_string_includelist = 52456496;</code>
     *
     * @param value The bytes of the queryStringIncludelist to add.
     * @return This builder for chaining.
     */
    public Builder addQueryStringIncludelistBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureQueryStringIncludelistIsMutable();
      queryStringIncludelist_.add(value);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.compute.v1.CacheKeyPolicy)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.compute.v1.CacheKeyPolicy)
  private static final com.google.cloud.compute.v1.CacheKeyPolicy DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.compute.v1.CacheKeyPolicy();
  }

  public static com.google.cloud.compute.v1.CacheKeyPolicy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CacheKeyPolicy> PARSER =
      new com.google.protobuf.AbstractParser<CacheKeyPolicy>() {
        @java.lang.Override
        public CacheKeyPolicy parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CacheKeyPolicy(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<CacheKeyPolicy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CacheKeyPolicy> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.compute.v1.CacheKeyPolicy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
