/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface CacheKeyPolicyOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.CacheKeyPolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * If true, requests to different hosts will be cached separately.
   * </pre>
   *
   * <code>bool include_host = 486867679;</code>
   *
   * @return Whether the includeHost field is set.
   */
  boolean hasIncludeHost();
  /**
   *
   *
   * <pre>
   * If true, requests to different hosts will be cached separately.
   * </pre>
   *
   * <code>bool include_host = 486867679;</code>
   *
   * @return The includeHost.
   */
  boolean getIncludeHost();

  /**
   *
   *
   * <pre>
   * If true, http and https requests will be cached separately.
   * </pre>
   *
   * <code>bool include_protocol = 303507535;</code>
   *
   * @return Whether the includeProtocol field is set.
   */
  boolean hasIncludeProtocol();
  /**
   *
   *
   * <pre>
   * If true, http and https requests will be cached separately.
   * </pre>
   *
   * <code>bool include_protocol = 303507535;</code>
   *
   * @return The includeProtocol.
   */
  boolean getIncludeProtocol();

  /**
   *
   *
   * <pre>
   * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
   * </pre>
   *
   * <code>bool include_query_string = 474036639;</code>
   *
   * @return Whether the includeQueryString field is set.
   */
  boolean hasIncludeQueryString();
  /**
   *
   *
   * <pre>
   * If true, include query string parameters in the cache key according to query_string_includelist and query_string_excludelist. If neither is set, the entire query string will be included. If false, the query string will be excluded from the cache key entirely.
   * </pre>
   *
   * <code>bool include_query_string = 474036639;</code>
   *
   * @return The includeQueryString.
   */
  boolean getIncludeQueryString();

  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @return A list containing the queryStringExcludelist.
   */
  java.util.List<java.lang.String> getQueryStringExcludelistList();
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @return The count of queryStringExcludelist.
   */
  int getQueryStringExcludelistCount();
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @param index The index of the element to return.
   * @return The queryStringExcludelist at the given index.
   */
  java.lang.String getQueryStringExcludelist(int index);
  /**
   *
   *
   * <pre>
   * Names of query string parameters to exclude in cache keys. All other parameters will be included. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_excludelist = 354964742;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the queryStringExcludelist at the given index.
   */
  com.google.protobuf.ByteString getQueryStringExcludelistBytes(int index);

  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @return A list containing the queryStringIncludelist.
   */
  java.util.List<java.lang.String> getQueryStringIncludelistList();
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @return The count of queryStringIncludelist.
   */
  int getQueryStringIncludelistCount();
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @param index The index of the element to return.
   * @return The queryStringIncludelist at the given index.
   */
  java.lang.String getQueryStringIncludelist(int index);
  /**
   *
   *
   * <pre>
   * Names of query string parameters to include in cache keys. All other parameters will be excluded. Either specify query_string_includelist or query_string_excludelist, not both. '&amp;' and '=' will be percent encoded and not treated as delimiters.
   * </pre>
   *
   * <code>repeated string query_string_includelist = 52456496;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the queryStringIncludelist at the given index.
   */
  com.google.protobuf.ByteString getQueryStringIncludelistBytes(int index);
}
