/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface SecurityPolicyAdvancedOptionsConfigOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.JsonParsing json_parsing = 282493529;
   * </code>
   *
   * @return Whether the jsonParsing field is set.
   */
  boolean hasJsonParsing();
  /**
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.JsonParsing json_parsing = 282493529;
   * </code>
   *
   * @return The enum numeric value on the wire for jsonParsing.
   */
  int getJsonParsingValue();
  /**
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.JsonParsing json_parsing = 282493529;
   * </code>
   *
   * @return The jsonParsing.
   */
  com.google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.JsonParsing getJsonParsing();

  /**
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.LogLevel log_level = 140582601;
   * </code>
   *
   * @return Whether the logLevel field is set.
   */
  boolean hasLogLevel();
  /**
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.LogLevel log_level = 140582601;
   * </code>
   *
   * @return The enum numeric value on the wire for logLevel.
   */
  int getLogLevelValue();
  /**
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.LogLevel log_level = 140582601;
   * </code>
   *
   * @return The logLevel.
   */
  com.google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig.LogLevel getLogLevel();
}
