/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/compute/v1/compute.proto

package com.google.cloud.compute.v1;

public interface SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfigOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.compute.v1.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * If set to true, enables CAAP for L7 DDoS detection.
   * </pre>
   *
   * <code>bool enable = 311764355;</code>
   *
   * @return Whether the enable field is set.
   */
  boolean hasEnable();
  /**
   *
   *
   * <pre>
   * If set to true, enables CAAP for L7 DDoS detection.
   * </pre>
   *
   * <code>bool enable = 311764355;</code>
   *
   * @return The enable.
   */
  boolean getEnable();

  /**
   *
   *
   * <pre>
   * Rule visibility can be one of the following: STANDARD - opaque rules. (default) PREMIUM - transparent rules.
   * </pre>
   *
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfig.RuleVisibility rule_visibility = 453258293;
   * </code>
   *
   * @return Whether the ruleVisibility field is set.
   */
  boolean hasRuleVisibility();
  /**
   *
   *
   * <pre>
   * Rule visibility can be one of the following: STANDARD - opaque rules. (default) PREMIUM - transparent rules.
   * </pre>
   *
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfig.RuleVisibility rule_visibility = 453258293;
   * </code>
   *
   * @return The enum numeric value on the wire for ruleVisibility.
   */
  int getRuleVisibilityValue();
  /**
   *
   *
   * <pre>
   * Rule visibility can be one of the following: STANDARD - opaque rules. (default) PREMIUM - transparent rules.
   * </pre>
   *
   * <code>
   * .google.cloud.compute.v1.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfig.RuleVisibility rule_visibility = 453258293;
   * </code>
   *
   * @return The ruleVisibility.
   */
  com.google.cloud.compute.v1.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfig
          .RuleVisibility
      getRuleVisibility();
}
