/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.compute.nativeimage;

import com.google.api.gax.nativeimage.NativeImageUtils;
import com.google.common.collect.ImmutableList;
import com.oracle.svm.core.annotate.AutomaticFeature;
import org.graalvm.nativeimage.hosted.Feature;

@AutomaticFeature
class ComputeFeature implements Feature {

  private static final ImmutableList<String> protoGoogleCommonProtosClasses =
      ImmutableList.of(
          "com.google.protobuf.DescriptorProtos$FieldOptions$Builder",
          "com.google.protobuf.DescriptorProtos$FieldOptions$CType",
          "com.google.protobuf.DescriptorProtos$FieldOptions$JSType",
          "com.google.protobuf.DescriptorProtos$FieldOptions",
          "com.google.protobuf.DescriptorProtos$MethodOptions$Builder",
          "com.google.protobuf.DescriptorProtos$MethodOptions$IdempotencyLevel",
          "com.google.protobuf.DescriptorProtos$MethodOptions",
          "com.google.protobuf.DescriptorProtos$ServiceOptions$Builder",
          "com.google.protobuf.DescriptorProtos$ServiceOptions",
          "com.google.protobuf.DescriptorProtos$UninterpretedOption",
          "com.google.api.FieldBehavior",
          "com.google.cloud.OperationResponseMapping");

  private static final ImmutableList<String> computeClasses;

  static {
    ImmutableList.Builder<String> computeClassesBuilder = ImmutableList.builder();
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AccessConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Address");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AttachedDisk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Autoscaler");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucket");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucketList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendService");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BulkInsertInstanceResource");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CacheInvalidationRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Commitment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DeprecationStatus");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Disk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskMoveRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksAddResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksRemoveResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksResizeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisplayDevice");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExchangedPeeringRoutesList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGateway");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGatewayList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Firewall");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.FirewallPoliciesListAssociationsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyAssociation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRuleAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRuleList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalNetworkEndpointGroupsAttachEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalNetworkEndpointGroupsDetachEndpointsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalOrganizationSetPolicyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalSetPolicyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GuestAttributes");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheck");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckService");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckServicesList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthChecksAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Image");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ImageFamilyView");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ImageList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Instance");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroup");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManager");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersAbandonInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersApplyUpdatesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersCreateInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersDeleteInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersDeletePerInstanceConfigsReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListErrorsResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListManagedInstancesResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListPerInstanceConfigsResp");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersPatchPerInstanceConfigsReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersRecreateInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersSetInstanceTemplateRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersSetTargetPoolsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersUpdatePerInstanceConfigsReq");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsAddInstancesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsListInstancesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsRemoveInstancesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsSetNamedPortsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceListReferrers");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceMoveRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceTemplate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceTemplateList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesAddResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesGetEffectiveFirewallsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesRemoveResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMachineResourcesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMachineTypeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMinCpuPlatformRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetServiceAccountRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesStartWithEncryptionKeyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Interconnect");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocationList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectsGetDiagnosticsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.License");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseCode");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicensesListResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineImage");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineImageList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Metadata");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Network");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEdgeSecurityService");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEdgeSecurityServiceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroup");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsAttachEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsDetachEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsListEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsListNetworkEndpoints");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkInterface");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksAddPeeringRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksGetEffectiveFirewallsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksRemovePeeringRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksUpdatePeeringRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroup");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsAddNodesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsDeleteNodesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsListNodes");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsSetNodeTemplateRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplateAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplateList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpoint");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpointList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Operation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroring");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Policy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Project");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsDisableXpnResourceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsEnableXpnResourceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsGetXpnResources");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsListXpnHostsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsSetDefaultNetworkTierRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicAdvertisedPrefix");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicAdvertisedPrefixList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefix");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefixAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefixList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Region");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionAutoscalerList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDiskTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDisksAddResourcePoliciesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionDisksRemoveResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDisksResizeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerDeleteInstanceConfigReq");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupManagerList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerPatchInstanceConfigReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerUpdateInstanceConfigReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersAbandonInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersApplyUpdatesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersCreateInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersDeleteInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListErrorsResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListInstanceConfigsResp");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListInstancesResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersRecreateRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersSetTargetPoolsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersSetTemplateRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsListInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsSetNamedPortsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionNetworkFirewallPoliciesGetEffectiveFirewallsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionSetPolicyRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionTargetHttpsProxiesSetSslCertificatesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionUrlMapsValidateRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Reservation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationsResizeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourceGroupReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Route");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouteList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Router");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterStatusResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Scheduling");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Screenshot");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPoliciesAggregatedList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SecurityPoliciesListPreconfiguredExpressionSetsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SerialPortOutput");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIdentity");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIntegrityPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SignedUrlKey");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Snapshot");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SnapshotList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPoliciesList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SslPoliciesListAvailableFeaturesResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPolicyReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Subnetwork");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworksExpandIpCidrRangeRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SubnetworksSetPrivateIpGoogleAccessRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Tags");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetGrpcProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetGrpcProxyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxyAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxyList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetHttpsProxiesSetQuicOverrideRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetHttpsProxiesSetSslCertificatesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxyAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstance");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstanceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstanceList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPool");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsAddHealthCheckRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsAddInstanceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsRemoveHealthCheckRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsRemoveInstanceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetReference");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetBackendServiceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxiesSetProxyHeaderRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetSslCertificatesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxyList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetTcpProxiesSetBackendServiceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxiesSetProxyHeaderRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGateway");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewayAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewayList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TestPermissionsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMap");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsValidateRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsableSubnetworksAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsageExportLocation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VmEndpointNatMappingsList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGateway");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewaysGetStatusResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnel");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Zone");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneSetPolicyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorType$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypeAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypeList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AccessConfig$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Address$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AttachedDisk$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Autoscaler$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucket$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucketList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendService$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BulkInsertInstanceResource$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CacheInvalidationRule$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Commitment$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DeprecationStatus$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Disk$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskMoveRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskType$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypeAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypeList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.DisksAddResourcePoliciesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.DisksRemoveResourcePoliciesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksResizeRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisplayDevice$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExchangedPeeringRoutesList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGateway$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGatewayList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Firewall$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.FirewallPoliciesListAssociationsResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyAssociation$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyRule$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRule$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRuleAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRuleList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalNetworkEndpointGroupsAttachEndpointsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalNetworkEndpointGroupsDetachEndpointsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalOrganizationSetPolicyRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalSetLabelsRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalSetPolicyRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GuestAttributes$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheck$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckService$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckServicesList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthChecksAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Image$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ImageFamilyView$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ImageList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Instance$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroup$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManager$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagerAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersAbandonInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersApplyUpdatesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersCreateInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersDeleteInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersDeletePerInstanceConfigsReq$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListErrorsResponse$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListManagedInstancesResponse$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListPerInstanceConfigsResp$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersPatchPerInstanceConfigsReq$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersRecreateInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersSetInstanceTemplateRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersSetTargetPoolsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersUpdatePerInstanceConfigsReq$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupsAddInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupsListInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupsRemoveInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupsSetNamedPortsRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceListReferrers$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceMoveRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceReference$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceTemplate$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceTemplateList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesAddResourcePoliciesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesGetEffectiveFirewallsResponse$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesRemoveResourcePoliciesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetLabelsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesSetMachineResourcesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMachineTypeRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesSetMinCpuPlatformRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesSetServiceAccountRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesStartWithEncryptionKeyRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Interconnect$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachment$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InterconnectAttachmentAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocation$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocationList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InterconnectsGetDiagnosticsResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.License$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseCode$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicensesListResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineImage$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineImageList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineType$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypeAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypeList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Metadata$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Network$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEdgeSecurityService$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEdgeSecurityServiceAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroup$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsAttachEndpointsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsDetachEndpointsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsListEndpointsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsListNetworkEndpoints$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkInterface$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksAddPeeringRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworksGetEffectiveFirewallsResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksRemovePeeringRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksUpdatePeeringRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroup$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsAddNodesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsDeleteNodesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsListNodes$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NodeGroupsSetNodeTemplateRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplate$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplateAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplateList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeType$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypeAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypeList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpoint$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpointList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Operation$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroring$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Policy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Project$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.ProjectsDisableXpnResourceRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.ProjectsEnableXpnResourceRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsGetXpnResources$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsListXpnHostsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.ProjectsSetDefaultNetworkTierRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicAdvertisedPrefix$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicAdvertisedPrefixList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefix$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.PublicDelegatedPrefixAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefixList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Region$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionAutoscalerList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDiskTypeList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionDisksAddResourcePoliciesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionDisksRemoveResourcePoliciesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDisksResizeRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerDeleteInstanceConfigReq$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupManagerList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerPatchInstanceConfigReq$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerUpdateInstanceConfigReq$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersAbandonInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersApplyUpdatesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersCreateInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersDeleteInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListErrorsResponse$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListInstanceConfigsResp$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListInstancesResponse$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersRecreateRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersSetTargetPoolsRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersSetTemplateRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsListInstancesRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsSetNamedPortsRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionNetworkFirewallPoliciesGetEffectiveFirewallsResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionSetLabelsRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionSetPolicyRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionTargetHttpsProxiesSetSslCertificatesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionUrlMapsValidateRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Reservation$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationsResizeRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourceGroupReference$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Route$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouteList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Router$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterStatusResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Scheduling$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Screenshot$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPoliciesAggregatedList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SecurityPoliciesListPreconfiguredExpressionSetsResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyReference$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyRule$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SerialPortOutput$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachment$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.ServiceAttachmentAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceConfig$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIdentity$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.ShieldedInstanceIntegrityPolicy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SignedUrlKey$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Snapshot$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SnapshotList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificate$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPoliciesList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SslPoliciesListAvailableFeaturesResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPolicy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPolicyReference$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Subnetwork$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SubnetworksExpandIpCidrRangeRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SubnetworksSetPrivateIpGoogleAccessRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Tags$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetGrpcProxy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetGrpcProxyList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxyAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxyList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetHttpsProxiesSetQuicOverrideRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetHttpsProxiesSetSslCertificatesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxyAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxyList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstance$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstanceAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstanceList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPool$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetPoolsAddHealthCheckRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsAddInstanceRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetPoolsRemoveHealthCheckRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetPoolsRemoveInstanceRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetReference$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetBackendServiceRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetProxyHeaderRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetSslCertificatesRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxyList$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetTcpProxiesSetBackendServiceRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetTcpProxiesSetProxyHeaderRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxyList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGateway$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewayAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewayList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TestPermissionsRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMap$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapReference$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsValidateRequest$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.UsableSubnetworksAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsageExportLocation$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VmEndpointNatMappingsList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGateway$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewaysGetStatusResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnel$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelAggregatedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Zone$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneSetLabelsRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneSetPolicyRequest$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Accelerators");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AdvancedMachineFeatures");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AliasIpRange");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Allowed");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AuditConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalingPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Backend");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucketCdnPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceGroupHealth");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Binding");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CustomerEncryptionKey");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CustomerEncryptionKeyProtectedDisk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Error");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExchangedPeeringRoute");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGatewayInterface");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyRuleMatcher");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GRPCHealthCheck");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GuestAttributesValue");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GuestOsFeature");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HttpRouteAction");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerAutoHealingPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsListInstances");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceManagedByIgmError");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceProperties");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstancesGetEffectiveFirewallsResponseEffectiveFirewallPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentPartnerMetadata");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectCircuitInfo");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectDiagnostics");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocationRegionInfo");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Items");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseCodeLicenseAlias");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseResourceCommitment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseResourceRequirements");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ManagedInstance");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MetadataFilter");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NamedPort");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpoint");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupAppEngine");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointWithHealthStatus");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkPeering");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworksGetEffectiveFirewallsResponseEffectiveFirewallPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupAutoscalingPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupNode");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpointGrpcSettings");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringForwardingRuleInfo");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PerInstanceConfig");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.PublicAdvertisedPrefixPublicDelegatedPrefix");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.PublicDelegatedPrefixPublicDelegatedSubPrefix");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Quota");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Reference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupsListInstances");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionNetworkFirewallPoliciesGetEffectiveFirewallsResponseEffectiveFirewallPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyGroupPlacementPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouteAsPath");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterBgp");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterStatus");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SchedulingNodeAffinity");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPoliciesWafConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyAdaptiveProtectionConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyRuleHttpHeaderAction");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentConnectedEndpoint");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShareSettings");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIdentityEntry");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateManagedSslCertificate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkLogConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxiesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolInstanceHealth");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TestPermissionsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsValidateResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsableSubnetwork");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VmEndpointNatMappings");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayStatus");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayVpnGatewayInterface");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Warning");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Warnings");
    computeClassesBuilder.add("com.google.cloud.compute.v1.XpnHostList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.XpnResourceId");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AllocationSpecificSKUReservation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AttachedDiskInitializeParams");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerStatusDetails");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalersScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucketCdnPolicy$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceCdnPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceGroupHealth$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServicesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ConfidentialInstanceConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CustomerEncryptionKey$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Denied");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExchangedPeeringRoute$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyRuleSecureTag");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.ForwardingRuleServiceDirectoryRegistration");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRulesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GuestAttributesValue$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HTTP2HealthCheck");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthChecksScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HttpRedirectAction");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerActionsSummary");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagersScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsListInstances$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceManagedByIgmError$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentPrivateInfo");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectDiagnostics$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectOutageNotification");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseResourceRequirements$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LocalDisk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LocationPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ManagedInstance$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEdgeSecurityServicesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupCloudFunction");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupsScopedList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointWithHealthStatus$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkRoutingConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupMaintenanceWindow");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupNode$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplatesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypesScopedList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NotificationEndpointGrpcSettings$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Operation$Status");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringFilter");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PerInstanceConfig$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefixesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RawDisk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Reference$Builder");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsListInstances$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourceCommitment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePoliciesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyInstanceSchedulePolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterBgpPeer");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterStatus$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RoutersScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Rule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SavedDisk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ScratchDisks");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPoliciesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPoliciesWafConfig$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyAdvancedOptionsConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyRuleMatcher");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentConsumerProjectLimit");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIdentityEntry$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SourceInstanceParams");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SslCertificateSelfManagedSslCertificate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificatesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkSecondaryRange");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworksScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxiesScopedList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxiesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstancesScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolInstanceHealth$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewaysScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TestPermissionsResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsValidateResponse$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsableSubnetwork$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VmEndpointNatMappings$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayStatus$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewaysScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelsScopedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.XpnHostList$Builder");
    computeClassesBuilder.add("com.google.cloud.compute.v1.XpnResourceId$Builder");

    computeClasses = computeClassesBuilder.build();
  }

  @Override
  public void beforeAnalysis(BeforeAnalysisAccess access) {
    for (String targetClass : protoGoogleCommonProtosClasses) {
      if (access.findClassByName(targetClass) != null) {
        NativeImageUtils.registerClassForReflection(access, targetClass);
      }
    }

    for (String targetClass : computeClasses) {
      if (access.findClassByName(targetClass) != null) {
        NativeImageUtils.registerClassForReflection(access, targetClass);
      }
    }
  }
}
