/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.compute.nativeimage;

import com.google.api.gax.nativeimage.NativeImageUtils;
import com.google.common.collect.ImmutableList;
import com.oracle.svm.core.annotate.AutomaticFeature;
import org.graalvm.nativeimage.hosted.Feature;

@AutomaticFeature
class ComputeFeature implements Feature {

  private static final ImmutableList<String> protoGoogleCommonProtosClasses =
      ImmutableList.of(
          "com.google.protobuf.DescriptorProtos$FieldOptions$Builder",
          "com.google.protobuf.DescriptorProtos$FieldOptions$CType",
          "com.google.protobuf.DescriptorProtos$FieldOptions$JSType",
          "com.google.protobuf.DescriptorProtos$FieldOptions",
          "com.google.protobuf.DescriptorProtos$MethodOptions$Builder",
          "com.google.protobuf.DescriptorProtos$MethodOptions$IdempotencyLevel",
          "com.google.protobuf.DescriptorProtos$MethodOptions",
          "com.google.protobuf.DescriptorProtos$ServiceOptions$Builder",
          "com.google.protobuf.DescriptorProtos$ServiceOptions",
          "com.google.protobuf.DescriptorProtos$UninterpretedOption",
          "com.google.api.FieldBehavior",
          "com.google.cloud.OperationResponseMapping");

  private static final ImmutableList<String> computeClasses;

  static {
    ImmutableList.Builder<String> computeClassesBuilder = ImmutableList.builder();
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AcceleratorTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AccessConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Address");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AddressList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AttachedDisk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Autoscaler");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.AutoscalerList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucket");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendBucketList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendService");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BackendServiceList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.BulkInsertInstanceResource");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CacheInvalidationRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Commitment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.CommitmentList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DeprecationStatus");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Disk");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskMoveRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DiskTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksAddResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksRemoveResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisksResizeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.DisplayDevice");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExchangedPeeringRoutesList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGateway");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ExternalVpnGatewayList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Firewall");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.FirewallPoliciesListAssociationsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyAssociation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.FirewallPolicyRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRuleAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ForwardingRuleList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalNetworkEndpointGroupsAttachEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.GlobalNetworkEndpointGroupsDetachEndpointsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalOrganizationSetPolicyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GlobalSetPolicyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.GuestAttributes");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheck");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckService");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthCheckServicesList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.HealthChecksAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Image");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ImageFamilyView");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ImageList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Instance");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroup");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManager");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupManagerList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersAbandonInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersApplyUpdatesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersCreateInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersDeleteInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersDeletePerInstanceConfigsReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListErrorsResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListManagedInstancesResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersListPerInstanceConfigsResp");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersPatchPerInstanceConfigsReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersRecreateInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersSetInstanceTemplateRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersSetTargetPoolsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.InstanceGroupManagersUpdatePerInstanceConfigsReq");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsAddInstancesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsListInstancesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsRemoveInstancesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceGroupsSetNamedPortsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceListReferrers");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceMoveRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceTemplate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstanceTemplateList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesAddResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesGetEffectiveFirewallsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesRemoveResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMachineResourcesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMachineTypeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetMinCpuPlatformRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesSetServiceAccountRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InstancesStartWithEncryptionKeyRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Interconnect");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectAttachmentList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectLocationList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.InterconnectsGetDiagnosticsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.License");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicenseCode");
    computeClassesBuilder.add("com.google.cloud.compute.v1.LicensesListResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineImage");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineImageList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.MachineTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Metadata");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Network");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEdgeSecurityService");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEdgeSecurityServiceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroup");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkEndpointGroupList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsAttachEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsDetachEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsListEndpointsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.NetworkEndpointGroupsListNetworkEndpoints");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkInterface");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworkList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksAddPeeringRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksGetEffectiveFirewallsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksRemovePeeringRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NetworksUpdatePeeringRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroup");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsAddNodesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsDeleteNodesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsListNodes");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeGroupsSetNodeTemplateRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplateAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTemplateList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeType");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypeAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NodeTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpoint");
    computeClassesBuilder.add("com.google.cloud.compute.v1.NotificationEndpointList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Operation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.OperationList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroring");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PacketMirroringList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Policy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Project");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsDisableXpnResourceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsEnableXpnResourceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsGetXpnResources");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsListXpnHostsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ProjectsSetDefaultNetworkTierRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicAdvertisedPrefix");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicAdvertisedPrefixList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefix");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefixAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.PublicDelegatedPrefixList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Region");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionAutoscalerList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDiskTypeList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDisksAddResourcePoliciesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionDisksRemoveResourcePoliciesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionDisksResizeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerDeleteInstanceConfigReq");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionInstanceGroupManagerList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerPatchInstanceConfigReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagerUpdateInstanceConfigReq");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersAbandonInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersApplyUpdatesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersCreateInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersDeleteInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListErrorsResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListInstanceConfigsResp");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersListInstancesResponse");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersRecreateRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersSetTargetPoolsRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupManagersSetTemplateRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsListInstancesRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionInstanceGroupsSetNamedPortsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionNetworkFirewallPoliciesGetEffectiveFirewallsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionSetPolicyRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.RegionTargetHttpsProxiesSetSslCertificatesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RegionUrlMapsValidateRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Reservation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ReservationsResizeRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourceGroupReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ResourcePolicyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Route");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouteList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Router");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.RouterStatusResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Scheduling");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Screenshot");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPoliciesAggregatedList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SecurityPoliciesListPreconfiguredExpressionSetsResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SecurityPolicyRule");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SerialPortOutput");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachment");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ServiceAttachmentList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceConfig");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIdentity");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ShieldedInstanceIntegrityPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SignedUrlKey");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Snapshot");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SnapshotList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificate");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslCertificateList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPoliciesList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SslPoliciesListAvailableFeaturesResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPolicy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SslPolicyReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Subnetwork");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworkList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.SubnetworksExpandIpCidrRangeRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.SubnetworksSetPrivateIpGoogleAccessRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Tags");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetGrpcProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetGrpcProxyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxyAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpProxyList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetHttpsProxiesSetQuicOverrideRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetHttpsProxiesSetSslCertificatesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxyAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetHttpsProxyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstance");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstanceAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetInstanceList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPool");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsAddHealthCheckRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsAddInstanceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsRemoveHealthCheckRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetPoolsRemoveInstanceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetReference");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetBackendServiceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxiesSetProxyHeaderRequest");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetSslProxiesSetSslCertificatesRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetSslProxyList");
    computeClassesBuilder.add(
        "com.google.cloud.compute.v1.TargetTcpProxiesSetBackendServiceRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxiesSetProxyHeaderRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxy");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetTcpProxyList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGateway");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewayAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TargetVpnGatewayList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.TestPermissionsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMap");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapReference");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UrlMapsValidateRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsableSubnetworksAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.UsageExportLocation");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VmEndpointNatMappingsList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGateway");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewayList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnGatewaysGetStatusResponse");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnel");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelAggregatedList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.VpnTunnelList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.Zone");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneList");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneSetLabelsRequest");
    computeClassesBuilder.add("com.google.cloud.compute.v1.ZoneSetPolicyRequest");
    computeClasses = computeClassesBuilder.build();
  }

  @Override
  public void beforeAnalysis(BeforeAnalysisAccess access) {
    for (String targetClass : protoGoogleCommonProtosClasses) {
      if (access.findClassByName(targetClass) != null) {
        NativeImageUtils.registerClassForReflection(access, targetClass);
      }
    }

    for (String targetClass : computeClasses) {
      if (access.findClassByName(targetClass) != null) {
        NativeImageUtils.registerClassForReflection(access, targetClass);
      }
    }
  }
}
